apiVersion: certificate.println.kr/v1alpha1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: certificate-operator
    app.kubernetes.io/managed-by: kustomize
  name: certificate-sample
spec:
  # TODO(user): Add fields here
